---

- hosts: leafs
  connection: local
  gather_facts: no 
  vars_files:
  - "vars/all.yaml"

  tasks:
  - name: BGP on leaf switches
    eos_config:
      src: templates/bgp_leaf.j2
      provider: "{{ eos_connection }}"

  - name: Connectivity checker
    eos_command:
      commands:
        - ping {{ item }}
      provider: '{{ eos_connection }}'
    register: result
    failed_when: "'connect: Network is unreachable' in result.stdout"
    with_items: "{{ ebgp_peers[inventory_hostname].keys() }}"    
